name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set execute permissions on gradlew
      run: chmod +x ./gradlew
      
#    - name: Update known_hosts
#     run: ssh -o StrictHostKeyChecking=no -v -p ${{ secrets.SSH_PORT }} -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_NETWORK_IP }} true

    - name: SSH Tunnel
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_NETWORK_IP: ${{ secrets.SSH_NETWORK_IP }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        # Start SSH agent and add the private key
        eval $(ssh-agent -s)
        ssh-add <(echo "$SSH_PRIVATE_KEY")

        # Create an SSH tunnel for MySQL
        ssh -f -N -L 3306:127.0.0.1:3306 $SSH_USERNAME@$SSH_NETWORK_IP -p $SSH_PORT

    - name: Build with Gradle
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        # Add error handling - exit if any command returns a non-zero status
        set -e

        # Execute Gradle build
        ./gradlew build

#    - name: Run Tests
#      env:
#        DB_HOST: 127.0.0.1
#        DB_PORT: ${{ secrets.DB_PORT }}
#        DB_NAME: ${{ secrets.DB_NAME }}
#        DB_USERNAME: ${{ secrets.DB_USERNAME }}
#        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#      run: |
#        # Add error handling - exit if any command returns a non-zero status
#        set -e
#
#        # Execute Gradle tests
#        ./gradlew test